### PR TITLE
Fix black picture bug for art style transfer.

### PR DESCRIPTION
**Pull request by cxxgtxy**
Adam is used in place of gradientdescent.
Parameter tuning.

### CODE REVIEW

**Comment by cxxgtxy** [comment]
Nick, please check the commit.
I have tested the style transfer result.

**Comment by nfmcclure** [comment]
Hi @cxxgtxy ,  Thanks for looking into this.  I've been quite busy with other projects at the moment. I will look at the code this weekend and merge it then.  Your help is greatly appreciated!

**Comment by cxxgtxy** [comment]
Welcome. 
Generally speaking, Adam is recommended for style transfer instead of SGD. So except for layer selection bug, I choose Adam.

**Comment by nfmcclure** [comment]
Just checked- it's working now. I don't think I would have found that layer selection issue.  Thanks so much.

**Pull request merged**
