### PR TITLE
updated notebook to api 1.0.1

### PR DESCRIPTION
**Pull request by jimthompson5802**
When I ran the notebook **05_nonlinear_svm.ipynb**, I encountered three errors.  The current code contain calls to `tf.neg` and `tf.sub`.  I modified those calls in the notebook to `tf.negative` and `tf.subtract`, respectively.  These corrections work with tensorflow api 1.0.1.  The changes occurred in code blocks designated [23] and [24]

I'm submitting this as a suggested correction.

### CODE REVIEW

**Comment by nfmcclure** [comment]
Thanks!

**Comment by jimthompson5802** [comment]
Nick,

I noticed in some of the other chapters there are only python modules (*.py).  

If you want to have equivalent jupyter notebooks and if it helps, I’m willing to take a stab at creating notebooks from the python modules and do the initial grunt work of breaking the python code into logical code chunks.

Let me know if you’d like me to do this and if there is a preferred sequence of chapters.

--------
James Thompson
Go For Broke!
Life is a fairy tale when you are flexible about happily ever after.
Life is non-linear, enjoy the curves

**Comment by nfmcclure** [comment]
Hi @jimthompson5802 ,

Thanks for the offer! I really want a way to go through the code and update it and creating the jupyter notebooks is a way for me.  But if you want to, I haven't touched the Nearest neighbors chapter (chapter 5).  It will probably be the last chapter I get around to converting to notebooks.  If you want to, start there.

Really, start anywhere you want to.  I'll review the pull requests and modify as needed. Thanks again!
-Nick

**Comment by jimthompson5802** [comment]
ok…will start with Chapter 5.

--------
James Thompson
Go For Broke!
Life is a fairy tale when you are flexible about happily ever after.
Life is non-linear, enjoy the curves

**Pull request merged**
